version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: sweetspot-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sweetspot
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - sweetspot-network

  # SweetSpot Application
  sweetspot-app:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile.dev
    container_name: sweetspot-app
    restart: unless-stopped
    ports:
      - "3001:3001"  # Backend API
      - "5173:5173"  # Frontend Dev Server
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/sweetspot?authSource=admin
      - JWT_SECRET=dev-jwt-secret-key-for-docker
      - PORT=3001
    volumes:
      - ../../:/app
      - /app/node_modules
      - ../../uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - sweetspot-network
    command: npm run dev

  # MongoDB Express (Database Admin UI)
  mongo-express:
    image: mongo-express:latest
    container_name: sweetspot-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - sweetspot-network

volumes:
  mongodb_data:

networks:
  sweetspot-network:
    driver: bridge